title: Following Github learning lab issue 4
author: GitHub User
email: qoolixiloop@gmx.ch
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Hi Googlers, this site holds my blog about anything and everything. 

# social links
twitter_username: not_on_twitter
github_username:  qoolixiloop

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
